---
title: "Wstępna analiza danych"
author: "USOSPredators"
date: "April 02, 2016"
output: html_document
---

## Wstęp
We read our data into R.

```{r, echo=FALSE}
library(plyr)
library(ggplot2)
library(dplyr)
```

```{r}
data <- read.csv("../data/database.txt", sep=";", dec=",")
```

Maly pokaz

```{r}
dat <- tbl_df(data)

analiza2Oceny <- dplyr:::filter(dat, NAZWA == "Analiza matematyczna inf. II") %>% dplyr:::select(OCENA_WARTOSC) %>% dplyr:::filter(OCENA_WARTOSC != '') %>% dplyr:::group_by(OCENA_WARTOSC) %>% dplyr:::summarise(ilosc = n())

ggplot(analiza2Oceny, aes(x=OCENA_WARTOSC, y=ilosc)) + geom_point()
```

Porównanie wyników z Analizy I oraz Analizy II

```{r}
dat <- tbl_df(data)

analiza1 <- dplyr:::filter(dat, NAZWA == "Analiza matematyczna inf. I") %>% dplyr:::select(OS_ID, OCENA_WARTOSC)

analiza2 <- dplyr:::filter(dat, NAZWA == "Analiza matematyczna inf. II") %>% dplyr:::select(OS_ID, OCENA_WARTOSC)

analiza <- merge(analiza1, analiza2, by = "OS_ID")

library(stringr)
analiza <- mutate(analiza, a1 = str_replace(OCENA_WARTOSC.x, ",", "."))
analiza <- mutate(analiza, a2 = str_replace(OCENA_WARTOSC.y, ",", "."))
analiza <- mutate(analiza, a1num = as.numeric(as.character(a1)))
analiza <- mutate(analiza, a2num = as.numeric(as.character(a2)))
analiza <- dplyr:::filter(analiza, a1num != "NA")
analiza <- dplyr:::filter(analiza, a2num != "NA")

analiza <- mutate(analiza, Roznica = a1num - a2num)

analizaGrupy = dplyr:::group_by(analiza, Roznica) %>% summarise(Ile = n())

ggplot(analizaGrupy, aes(x=Roznica, y=Ile)) + geom_point(size = analizaGrupy$Ile*0.4) + scale_x_continuous(limits = c(-2.5, 2.5)) + scale_y_continuous(limits = c(0, 250)) + ggtitle("Roznica w wynikach z Analizy I oraz Analizy II") + xlab("Roznica") + ylab("Ilosc osob") + theme(plot.title = element_text(size=20), axis.text=element_text(size=11), axis.title=element_text(size=20))
```


```{r}
md <- data[grepl("*MAD$", data$PRZ_KOD),] %>% dplyr:::select(OS_ID, OCENA_WARTOSC)
rpis <- data[grepl("*RPR$", data$PRZ_KOD),] %>% dplyr:::select(OS_ID, OCENA_WARTOSC)

porownanie <- merge(md, rpis, by = "OS_ID")
porownanie <- mutate(porownanie, a1 = str_replace(OCENA_WARTOSC.x, ",", "."))
porownanie <- mutate(porownanie, a2 = str_replace(OCENA_WARTOSC.y, ",", "."))
porownanie <- mutate(porownanie, a1num = as.numeric(as.character(a1)))
porownanie <- mutate(porownanie, a2num = as.numeric(as.character(a2)))
porownanie <- dplyr:::filter(porownanie, a1num != "NA")
porownanie <- dplyr:::filter(porownanie, a2num != "NA")

porownanie <- mutate(porownanie, Roznica = a1num - a2num)

porownanieGrupy = dplyr:::group_by(porownanie, Roznica) %>% summarise(Ile = n())

ggplot(porownanieGrupy, aes(x=Roznica, y=Ile)) + geom_point(size = porownanieGrupy$Ile*0.4) + scale_x_continuous(limits = c(-2.5, 2.5)) + scale_y_continuous(limits = c(0, 250)) + ggtitle("Roznica w wynikach z MD i RPiS") + xlab("Roznica") + ylab("Ilosc osob") + theme(plot.title = element_text(size=20), axis.text=element_text(size=12), axis.title=element_text(size=20))
```

## Porownanie wynikow w latach

<br>

```{r, echo=FALSE}
asd <- data[grepl("*ASD$", data$PRZ_KOD),]
asd <- asd[ grepl("^2010Z$|^2011Z$|^2012Z$", asd$CDYD_KOD),]

asdLata = dplyr:::group_by(asd, CDYD_KOD, OCENA_WARTOSC) %>% summarise(ILE = n())

p1 <- (
  ggplot(data=asdLata, aes(x=OCENA_WARTOSC, y=ILE, colour = CDYD_KOD))
  + geom_line(aes(group = CDYD_KOD)) + geom_point()
  + ggtitle("Porownanie wynikow ASD w poszczegolnych latach")
  + xlab("Ocena") + ylab("Ilosc osob")
  + labs(colour = "Rocznik")
)
p1
```

```{r, echo=FALSE}
md <- data[grepl("*MAD$", data$PRZ_KOD),]
md <- md[ grepl("^2009L$|^2010L$|^2011L$", md$CDYD_KOD),]

mdLata = dplyr:::group_by(md, CDYD_KOD, OCENA_WARTOSC) %>% summarise(ILE = n())

p2 <- (
  ggplot(data=mdLata, aes(x=OCENA_WARTOSC, y=ILE, colour = CDYD_KOD))
  + geom_line(aes(group = CDYD_KOD)) + geom_point()
  + ggtitle("Porownanie wynikow MD w poszczegolnych latach")
  + xlab("Ocena") + ylab("Ilosc osob")
  + labs(colour = "Rocznik")
)
p2
```



## Porownanie wynikow wykladowcow

<br>

```{r, echo=FALSE}
asd <- data[grepl("*ASD$", data$PRZ_KOD),]
asd <- asd[grepl("*WYK$", asd$TZAJ_KOD_1),]

asdWykladowcy =
  dplyr:::group_by(asd, PRAC_ID_1, OCENA_WARTOSC) %>%
  filter(OCENA_WARTOSC != "") %>%
  tally %>%
  group_by(PRAC_ID_1) %>%
  mutate(PCT=n/sum(n))


p3 <- (
  ggplot(data=asdWykladowcy, aes(x=OCENA_WARTOSC, y=PCT, colour = as.factor(PRAC_ID_1)))
  + geom_line(aes(group = PRAC_ID_1)) + geom_point()
  + scale_y_continuous(labels = scales::percent)
  + ggtitle("Porownanie wynikow roznych wykladowcow ASD")
  + xlab("Ocena") + ylab("Liczba osob uzyskujaca dany wynik")
  + labs(colour = "ID Wykladowcy")
)
p3
```

```{r, echo=FALSE}
md <- data[grepl("*MAD$", data$PRZ_KOD),]
md <- md[grepl("*WYK$", md$TZAJ_KOD_1),]


mdWykladowcy =
  dplyr:::group_by(md, PRAC_ID_1, OCENA_WARTOSC) %>%
  filter(OCENA_WARTOSC != "") %>%
  tally %>%
  group_by(PRAC_ID_1) %>%
  mutate(PCT=n/sum(n))


p4 <- (
  ggplot(data=mdWykladowcy, aes(x=OCENA_WARTOSC, y=PCT, colour = as.factor(PRAC_ID_1)))
  + geom_line(aes(group = PRAC_ID_1)) + geom_point()
  + scale_y_continuous(labels = scales::percent)
  + ggtitle("Porownanie wynikow roznych wykladowcow MD")
  + xlab("Ocena") + ylab("Liczba osob uzyskujaca dany wynik")
  + labs(colour = "ID Wykladowcy")
)
p4
```
