---
title: "Instrukcja instalacji i uĹĽytkowania pakietu maturiser"
author: "Team Rocket"
date: "May 31, 2016"
output: 
  html_document: 
    keep_md: yes
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## O pakiecie

Pakiet Maturiser dostarcza narzędzia do badania osiągnięć uczniów poszczególnych szkół. Dla wybranej szkoły pokaże jakie wyniki uzyskali jej uczniowie i porówna je z wynikami uczniów innych szkół w gminie jak i w kraju. Wyniki można porównywać ze względu na różne kryteria (np. liczba punktów jakie uczniowie szkoły uzyskaliby podczas rekrutacji na dziennikarstwo UW). Aplikacja wyświetla czytelny histogram przedstawiający rozkład punktów jakie uczniowie szkoły uzyskali w tym kryterium. W tle ich wyniki są porównywane z osiągnięciami uczniów w gminie i w kraju. Możliwe jest definiowanie własnych kryteriów porównawczych. Nasza aplikacja dostarcza w tym celu prosty framework.


## Instalacja i pierwsze uruchomienie

## Definiowanie własnych kryteriów porównawczych

## Dla użytkownika webservicu - instrukcja

