load('szkoly.RData', envir=.GlobalEnv)
load('all_data_geo.RData', envir=.GlobalEnv)
library(shiny)
library(shinydashboard)
library(RCurl)
library(RJSONIO)
library(dplyr)
library(leaflet)
library(htmltools)
library(tidyr)