---
title: "Instrukcja obsługi narzędzia"
output: html_document
---

Narzędzie służy do wyszukiwania najlepiej prezentujących się szkół w regionie wybranym przez użytkownika. 

Przed skorzystaniem z głównej funkcjonalności aplikacji, użytkownik powinien wybrać w panelu po lewej stronie rodzaj szkoły, który go interesuje (gimnazjum, liceum, itp.). Następnie należy wybrać części egzaminów, które mają być brane pod uwagę przy porównywaniu szkół danego rodzaju. Przykładowo uczeń, który jest zainteresowany profilami ścisłymi w liceum, powinien wybrać do oceny szkół ogólnokształcących wyniki z matury rozszerzonej z matematyki czy fizyki.
Dodatkowo użytkownik może wybrać dla każdego wybranego egzaminu wagę (0-100), z jaką dany egzamin będzie wpływał na końcowe porównanie szkół. Ostatnim elementem w panelu po lewej stronie jest wybór lat, z których wyniki będą uwzględnione w obliczeniach. 

Kiedy użytkownik wybierze wszystkie interesujące go kryteria opisane powyżej, może wybrać region Polski, w którym znajdują się szkoły, które chce porównać. W tym celu może w intuicyjny sposób przybliżyć dowolny fragment mapy widocznej po prawej stronie aplikacji. Na początku na mapie widoczne są klastry z liczbami, oznaczającymi liczbę szkół w danym obszarze. Przy dostatecznie dużym przybliżeniu mapy, klastry zamieniają się na kółka, reprezentujące poszczególne szkoły. Znaczniki odzwierciedlają położenie szkoły na mapie, a ich kolor oznacza jak prezentuje się szkoła na tle całego kraju. Im bardziej zielone jest kółko, tym lepsze wyniki uzyskała szkoła z wybranych wcześniej egzaminów w przeciągu wybranych lat. Analogicznie, im znacznik jest bardziej czerwony, tym gorzej prezentuje się szkoła w wybranych częściach egzaminu. 

Użytkownik ma możliwość kliknięcia na kółka reprezentujące szkoły w celu uzyskania bardziej szczegółowych danych, tj. nazwy szkoły oraz pozycji, którą szkoła zajmuje w kraju oraz w wybranym przez użytkownika obszarze, bazując na wybranych kryteriach oceny. Dodatkowo w górnym lewym rogu, użytkownik może przełączyć się z trybu mapy na tryb tabeli, w której ukażą mu się wszystkie szkoły z wybranego uprzednio obszaru, posortowane od tych najlepszych do tych, które radzą sobie najgorzej. 