---
title: "Korelacja wyników z matematyki: egzamin gimnazjalny i matura podstawowa"
author: "PB"
date: "March 8, 2016"
output:
  html_document: 
    fig_caption: yes
    fig_height: 7
    fig_width: 10
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#this.dir <- dirname(parent.frame(2)$ofile)
#setwd(this.dir)

library(ZPD)
library(rCharts)
```

##Pobieranie danych

```{r data download, eval = FALSE}
  src <- polacz()
  ucz <-pobierz_uczniow(src)
  mt_pods_mat_2015 <- pobierz_wyniki_egzaminu(src,
                                              rodzajEgzaminu = "matura",
                                              czescEgzaminu = "matematyka podstawowa",
                                              2015, TRUE)
  gm_mat_2012 <- pobierz_wyniki_egzaminu(src,
                                         rodzajEgzaminu = "egzamin gimnazjalny",
                                         czescEgzaminu = "matematyka",
                                         2012, TRUE)
  mt_pods_mat_2015 <- collect(mt_pods_mat_2015)
  gm_mat_2012 <- collect(gm_mat_2012)
  ucz <- collect(ucz)
  
  save(ucz, file = "ZPD_ucz.dat")
  save(mt_pods_mat_2015, file = "ZPD_pods_mat_2015.dat")
  save(gm_mat_2012, file = "ZPD_gm_mat_2012.dat")
```

##Ładowanie z pliku
```{r ladowanie}
load(file = "ZPD_ucz.dat")
load(file = "ZPD_pods_mat_2015.dat")
load(file = "ZPD_gm_mat_2012.dat")
```

##Przetwarzanie danych
```{r przetwarzanie}
mt_pods_mat_2015 %>%
  mutate(suma_pmat = rowSums(.[5:67], na.rm = TRUE)) %>%
  select(id_obserwacji, suma_pmat) -> sumy_pmat_2015

gm_mat_2012 %>%
  mutate(suma_gmat = rowSums(.[5:27], na.rm = TRUE)) %>%
  select(id_obserwacji, suma_gmat) -> sumy_gmat_2012

inner_join(sumy_pmat_2015, ucz, by = "id_obserwacji") %>%
  select(suma_pmat, id_cke, rocznik) -> sumy_pmat_2015

inner_join(sumy_gmat_2012, ucz, by = "id_obserwacji") %>%
  select(suma_gmat, id_cke, rocznik) -> sumy_gmat_2012

inner_join(sumy_gmat_2012, sumy_pmat_2015, by= "id_cke") %>%
  select(suma_gmat, suma_pmat) -> korelacja_gm_pm
```
## Wkres:

```{r korelacje}
smoothScatter(korelacja_gm_pm, nbin = 300,
              xlab = "Wynik egz gimnazjalnego - matematyka",
              ylab = "Wyniki matury z matematyki podstawowej")

```
