init <<- function() {

  regiony <<- data.frame()
  regiony$wojewodztwo <<- character(0)
  regiony$powiat <<- character(0)
  regiony$gmina <<- character(0)

  szkoly <<- data.frame()
  szkoly$id <<- integer(0)
  szkoly$rok <<- integer(0)
  szkoly$gmina <<- character(0)
  szkoly$powiat <<- character(0)
  szkoly$wojewodztwo <<- character(0)
  szkoly$nazwa <<- character(0)
  szkoly$typ <<- character(0)

  typy_testow <<- data.frame()
  typy_testow$id <<- integer(0)
  typy_testow$rodzaj_egzaminu <<- character(0)
  typy_testow$czesc_egzaminu <<- character(0)
  typy_testow$rok <<- integer(0)
  typy_testow$arkusz <<- character(0)

  wyniki_szkol <<- data.frame()
  wyniki_szkol$id <<- integer(0)
  wyniki_szkol$rodzaj_egzaminu <<- character(0)
  wyniki_szkol$czesc_egzaminu <<- character(0)
  wyniki_szkol$rok <<- integer(0)
  wyniki_szkol$sredni_wynik <<- numeric(0)
  wyniki_szkol$id_kryterium <<- character(0)

  kryteria <<- data.frame()
  kryteria$id <<- character(0)
  kryteria$numer_pytania <<- character(0)
  kryteria$id_pytania <<- character(0)
  kryteria$id_wiazki <<- character(0)
  kryteria$tresc_pytania <<- character(0)
  kryteria$tresc_wiazki <<- character(0)
  kryteria$numer_kryterium <<- character(0)
  kryteria$max_punktow <<- integer(0)

  wyniki_po_egz <<- data.frame()
  wyniki_po_egz$rok <<- numeric(0)
  wyniki_po_egz$kwantyl <<- numeric(0)
  wyniki_po_egz$rodzaj_egzaminu <<- character(0)
  wyniki_po_egz$czesc_egzaminu <<- character(0)
  wyniki_po_egz$rodzaj_poprzedni <<- character(0)
  wyniki_po_egz$czesc_poprzedni <<- character(0)
  wyniki_po_egz$id_kryterium <<- numeric(0)
  wyniki_po_egz$wynik <<- numeric(0)

  wyniki_po_plci <<- data.frame()
  wyniki_po_plci$rok <<- numeric(0)
  wyniki_po_plci$rodzaj_egzaminu <<- character(0)
  wyniki_po_plci$czesc_egzaminu <<- character(0)
  wyniki_po_plci$plec <<- character(0)
  wyniki_po_plci$id_kryterium <<- numeric(0)
  wyniki_po_plci$wynik <<- numeric(0)


  uczniowie <<- data.frame()
  uczniowie$id_obserwacji <<- integer(0)
  uczniowie$dysleksja <<- logical(0)
  uczniowie$plec <<- character(0)

  # Tabele pomocnicze
  oceny_uczniow <<- data.frame()
  oceny_uczniow$id_testu <<- integer(0)
  oceny_uczniow$id_szkoly <<- integer(0)
  oceny_uczniow$rodzaj_egzaminu <<- character(0)
  oceny_uczniow$czesc_egzaminu <<- character(0)
  oceny_uczniow$id_obserwacji <<- integer(0)
  oceny_uczniow$wynik <<- numeric(0)

  ostatnie_przystapienia <<- data.frame()
  ostatnie_przystapienia$id_testu <<- integer(0)
  ostatnie_przystapienia$rodzaj_egzaminu <<- character(0)
  ostatnie_przystapienia$czesc_egzaminu <<- character(0)
  ostatnie_przystapienia$rok <<- integer(0)
}
